name: attende
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.4.5  # Ensuring native splash support
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Ensure all images (PNG/SVG) are placed in this folder

#  fonts:
#    - family: Lobster
#      fonts:
#        - asset: assets/fonts/Lobster-Regular.ttf
#
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Medium.ttf


flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  branding: assets/images/bottom.png
  image: assets/images/branding.png  # Logo in splash screen
  background_image: assets/images/splash_gradient.png  # Background gradient

  android_12:
    image: assets/images/branding.png
    branding: assets/images/bottom.png
    icon_background_color: "#FFFFFF"
    fullscreen: true