name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK with a newer version that supports Dart SDK 3.x
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Make sure this version supports Dart SDK 3.x

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests in the test/ directory
      - name: Run tests
        run: flutter test
