name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # You can specify a different version if needed.

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      # This will ensure all Flutter code is formatted correctly.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests in the test/ directory
      - name: Run tests
        run: flutter test
