name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Flutter SDK with a stable version that supports Dart SDK 3.7.x
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # Make sure this version supports Dart SDK 3.x

      # Ensure Flutter dependencies are up-to-date
      - name: Install dependencies
        run: flutter pub get

      # Analyze the project for issues
      - name: Analyze project source
        run: flutter analyze

      # Run tests located in the test/ directory
      - name: Run tests
        run: flutter test
